name: Build Mod Jar
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Find build.gradle
        run: |
          echo "=== KLASÖR YAPISI ==="
          find . -maxdepth 3 -not -path '*/.*'
